"""add chat_bind for user

Revision ID: 9c58eb97a966
Revises: dbcfdd8d1c46
Create Date: 2024-06-19 20:05:08.612469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c58eb97a966'
down_revision: Union[str, None] = 'dbcfdd8d1c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('binded_chat', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'binded_chat')
    # ### end Alembic commands ###
