"""fix

Revision ID: d977c5519fca
Revises: 9c58eb97a966
Create Date: 2024-07-06 22:52:40.824273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd977c5519fca'
down_revision: Union[str, None] = '9c58eb97a966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('danbooru', 'default_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('danbooru', 'default_tags',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
