"""Initial commit

Revision ID: dbcfdd8d1c46
Revises: 
Create Date: 2024-06-16 19:28:53.270613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcfdd8d1c46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('banned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('danbooru',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('default_tags', sa.String(), nullable=False),
    sa.Column('default_count', sa.Integer(), nullable=False),
    sa.Column('tags_display', sa.Boolean(), nullable=False),
    sa.Column('score_display', sa.Boolean(), nullable=False),
    sa.Column('rating_display', sa.Boolean(), nullable=False),
    sa.Column('url_display', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('tg_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('danbooru')
    op.drop_table('users')
    # ### end Alembic commands ###
